jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          command: |
            apt-get install wget
            wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
            unzip -d /usr/local/bin terraform_0.11.10_linux_amd64.zip
            terraform init
            terraform fmt -check=true
version: 2
